### PR TITLE
Change the positioning of the vertical text to "float" less

### PR DESCRIPTION
**Pull request by tika**
Hope this works, lol.

### CODE REVIEW

**Comment by punctuations** [comment]
Looking good! One thing though, can you either delete the last commit (`git reset --hard HEAD^`) or rename it to follow the conventional commit scheme? (`git commit --amend -m "chore: merge branch 'main'"`)

**Review by punctuations — APPROVED** [review]
Changes are looking great!

**Comment by tika** [comment]
My like for GitHub has grown from a "ok, this is annoying" to a full on, spitting, red hot, everlasting, ember-making, life-taking, soul shaking, blazing fire that grows and grows by each day. GitHub is like that one voice in your head, the "are we nearly there yet" that keeps ringing and ringing, knowing that it will haunt you - that all your progress could just be for nothing. Applied on a universal scale, imagine if all the world's progress just vanished, _poof_, like a marshmallow in front of small child.

GitHub is not my favourite.

**Comment by alii** [comment]
thanks man

**Review by alii — COMMENTED** [review]
Thanks

**Comment by punctuations** [comment]
tfw

**Pull request closed without merging**
