### PR TITLE
fix: layout of vertical text

### PR DESCRIPTION
**Pull request by tika**
Fix the vertical text from being in the centre (e.g.):

before

to:
after

### CODE REVIEW

**Review by punctuations — APPROVED** [review]

**Comment by tika** [comment]
pov: changes were approved
funk

**Comment by punctuations** [comment]
> pov: changes were approved
> funk

tfw

**Comment by tika** [comment]
aight im going to bed now, pce.

**Comment by punctuations** [comment]
gn

**Comment by alii** [comment]
thanks man

**Pull request merged**
